### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by StarNumber12046** [maxmilton/new-tab#1671]
is it blazingly fast?

**Comment by maxmilton** [comment]
This is a fun project I use for playing with performance and file size optimisations. Yes, it is fast, however you're limited by your machine's CPU and disk read performance. If you have a lot of open tabs or a gigantic amount of bookmarks you may see some slowdown. Definitely more performance to squeeze out in those situations.

There are no formal speed benchmarks but you can try it and judge for yourself :)
