### ISSUE TITLE
"New Tab" in New Tab

### ISSUE THREAD

**Issue by JvilleDev** [maxmilton/new-tab#2080]
When I click on it, it closes the new tab. It shouldn't be visible by itself
![Error Img](https://github.com/maxmilton/new-tab/assets/90424405/fa56b2b2-0b65-49f3-b0a9-b6398ff7c17c)

**Comment by maxmilton** [comment]
It's useful to show the current "New Tab" page, as you can see where it is in relation to other tabs. Plus it's meant to be a list of _all_ open tabs.

I can see how it could be confusing to close the page when clicking on it though. Perhaps it should not be a clickable link, or at least not close the page.

**Comment by maxmilton** [comment]
Fixed in <https://github.com/maxmilton/new-tab/pull/2082> and released in <https://github.com/maxmilton/new-tab/releases/tag/v0.22.0>.

The updated version has been submitted to the Chrome Web Store, so it will start rolling out to user automatically soon.
