### ISSUE TITLE
[FEATURE REQUEST] Add option to follow system's theme

### ISSUE THREAD

**Issue by claudio4** [maxmilton/new-tab#2153]
# What is expected from this feature
To have an option, perhaps as an standalone option, perhaps just as another theme that chooses between light or dark mode following the systems preference, in other words, a theme that uses the CSS media feature `prefers-color-scheme`.

# How is this useful?
It would be beneficial for users who prefer to adjust their system theme according to ambient light conditions, as it would eliminate the need to navigate to the extensions menu to align the new tab theme. Moreover, setting this option as a default could enhance the initial user experience by aligning more closely with their theme preferences.

# Any further details
Since this can be implemented using [purely CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), it's unlikely that it would have any noticeable effect on performance.

**Comment by maxmilton** [comment]
I thought the same thing recently and actually added this feature last week in <https://github.com/maxmilton/new-tab/commit/8c646e776fa8d63e2e059659a73b5938e928fc66>. It will be the new default theme.

It's currently living in the `next` branch so you can either build that for yourself, or wait a while until I publish the next release.  I'll close this issue once a new version is published on the chrome web store.

**Comment by claudio4** [comment]
Glad to hear that it is already in the codebase. 
Thank you for making this extension. It just makes the new tab experience so much useful that it is a bliss to use.

**Comment by maxmilton** [comment]
Closing now as the change was merged and released in <https://github.com/maxmilton/new-tab/releases/tag/v0.23.0>. It's been submitted to the [Chrome Webstore](https://chrome.google.com/webstore/detail/new-tab/cpcibnbdmpmcmnkhoiilpnlaepkepknb) and once approved it will roll out to users.
