### ISSUE TITLE
Latest build 

### ISSUE THREAD

**Issue by hjyoung1** [maxmilton/new-tab#494]
How to download currently latest build v0.14.0 for chrome?
On webstore it's old version.

**Comment by maxmilton** [comment]
Took me a while (better late than never... right?!) but I'm finally getting close to another public release. The remaining release blockers are listed in <https://github.com/maxmilton/new-tab/issues/1118>.

Before a public release it's also possible to manually install using the [latest Github release](https://github.com/maxmilton/new-tab/releases) `chrome-extension.zip`.
