### ISSUE TITLE
Refactor the bookmark bar overflow functionality

### ISSUE THREAD

**Issue by maxmilton** [maxmilton/new-tab#622]
Durring the last big refactor I commented out the existing bookmark bar overflow code as I wasn't very happy with. How bookmark sub folders work needs to be completely refactored so as part of that work we should also write a new way to handle overflow.

TODO: Find some good virtual list implementations for insperation.

**Comment by fmal** [comment]
@MaxMilton can't express how useful this extension is, awesome job!
I have tons of bookmarks and lack of the overflow functionality is the only thing that frustrates me a bit.
Do you have plans on implementing and releasing 1.0.0 in the future?

**Comment by MaxMilton** [comment]
Thank you for your kind words.

If all you need is the basic features with bookmark overflow, version `v0.12.4` published [in the Chrome Web Store](https://chrome.google.com/webstore/detail/new-tab/cpcibnbdmpmcmnkhoiilpnlaepkepknb) does actually work.

The difference between that version and `master` is the code was completely refactored for file size and performance + I updated Svelte from v2 to v3. As part of the improvements, I couldn't get bookmark overflow to work just right so I put off finishing the refactor...

Finishing the refactor has been sitting in my todo list for far too long! I still use the extension every day so I can definitely see the benefit in fixing the remaining issues and getting a v1 released.

Thanks for the reminder. I'll have another crack at this as I have time on the upcoming weekends.

**Comment by maxmilton** [comment]
Fixed in https://github.com/maxmilton/new-tab/commit/e6ce5954a989bd37e120ca770f302ab65322516f and available from [v0.16.0](https://github.com/maxmilton/new-tab/releases).

Will be available publicly on the Chrome Web Store once I work through the release blockers in <https://github.com/maxmilton/new-tab/issues/1118>.
